source 'https://github.com/CocoaPods/Specs.git'

inhibit_all_warnings!
use_frameworks!
platform :ios, '11.0'

target 'ZZGuideController_Example' do
  pod 'ZZGuideController', :path => '../'

  target 'ZZGuideController_Tests' do
    inherit! :search_paths

    
  end
end
